#ifndef RES_RSA_CONFIG_H
#define RES_RSA_CONFIG_H

#cmakedefine VERSION "@VERSION@"
#cmakedefine BINDIR "@BIN_INSTALL_DIR"
#cmakedefine SBINDIR "@SBIN_INSTALL_DIR"
#cmakedefine SYSCONFDIR "@SYSCONF_INSTALL_DIR"
#cmakedefine LOCALSTATEDIR "@LOCALSTATE_INSTALL_DIR"
#cmakedefine MANDIR "@MAN_INSTALL_DIR"
#cmakedefine DATADIR "@DATA_INSTALL_DIR"
#cmakedefine LIBDIR "@LIB_INSTALL_DIR"

#cmakedefine HAVE_TIME_H

#cmakedefine SIZEOF_UNSIGNED_CHAR "SIZEOF_UNSIGNED_CHAR}
#cmakedefine SIZEOF_UNSIGNED_SHORT ${SIZEOF_UNSIGNED_SHORT}
#cmakedefine SIZEOF_UNSIGNED_INT ${SIZEOF_UNSIGNED_INT}
#cmakedefine SIZEOF_UNSIGNED_LONG ${SIZEOF_UNSIGNED_LONG}
#cmakedefine SIZEOF_UNSIGNED_LONG_LONG ${SIZEOF_UNSIGNED_LONG_LONG}
#cmakedefine SIZEOF_SIGNED_CHAR ${SIZEOF_SIGNED_CHAR}
#cmakedefine SIZEOF_SIGNED_SHORT ${SIZEOF_SIGNED_SHORT}
#cmakedefine SIZEOF_SIGNED_INT ${SIZEOF_SIGNED_INT}
#cmakedefine SIZEOF_SIGNED_LONG ${SIZEOF_SIGNED_LONG}
#cmakedefine SIZEOF_SIGNED_LONG_LONG ${SIZEOF_SIGNED_LONG_LONG}

#cmakedefine HAVE_STRFTIME


#endif